language: ruby
cache: bundler

install:
  - bundle install

script:
  - bundle exec jekyll build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: kaleid-liner/kaleid-liner.github.io
  target_branch: master
  keep_history: true
  on:
    branch: master

